# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from acmesky.models.base_model_ import Model
from acmesky import util


class BuyOfferResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, communication_code=None):  # noqa: E501
        """BuyOfferResponse - a model defined in OpenAPI

        :param communication_code: The communication_code of this BuyOfferResponse.  # noqa: E501
        :type communication_code: str
        """
        self.openapi_types = {
            'communication_code': str
        }

        self.attribute_map = {
            'communication_code': 'communication_code'
        }

        self._communication_code = communication_code

    @classmethod
    def from_dict(cls, dikt) -> 'BuyOfferResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BuyOfferResponse of this BuyOfferResponse.  # noqa: E501
        :rtype: BuyOfferResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def communication_code(self):
        """Gets the communication_code of this BuyOfferResponse.


        :return: The communication_code of this BuyOfferResponse.
        :rtype: str
        """
        return self._communication_code

    @communication_code.setter
    def communication_code(self, communication_code):
        """Sets the communication_code of this BuyOfferResponse.


        :param communication_code: The communication_code of this BuyOfferResponse.
        :type communication_code: str
        """
        if communication_code is None:
            raise ValueError("Invalid value for `communication_code`, must not be `None`")  # noqa: E501
        if communication_code is not None and len(communication_code) < 1:
            raise ValueError("Invalid value for `communication_code`, length must be greater than or equal to `1`")  # noqa: E501

        self._communication_code = communication_code
